workspace:
  base: /go
  path: src/github.com/alioygur/drone-example

pipeline:
  test:
    image: golang:latest
    commands:
      - go get ./...
      - go test

  build:
    image: docker
    commands:
      - docker build -t alioygur/drone-example .
    volumes:
      - /var/run/docker.sock:/var/run/docker.socks