workspace:
  base: /go
  path: src/github.com/alioygur/drone-example

pipeline:
  build:
    image: golang:latest
    commands:
      exit 0
      # - go get ./...
      # - go test
      # - go build